apiVersion: operators.coreos.com/v1beta1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: ixiatg-op.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: IxiaTG is the Schema for the ixiatgs API
      displayName: Ixia TG
      kind: IxiaTG
      name: ixiatgs.network.keysight.com
      version: v1beta1
  description: Ixia operator to serve KNE requests
  displayName: ixia-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - ixia
  links:
  - name: Ixiatg Op
    url: https://ixiatg-op.domain
  maintainers:
  - email: himanshu.ashwini@keysight.com
    name: namse
  maturity: alpha
  provider:
    name: ixia
  version: 0.0.0
